"""Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2
"""

for i in range(4000000):
    f = []
    while len(f) <= 2:
        if i % 2 == 0:
            f.append(i)
        return sum(f)

nums = [i for i in range(4000000) if i % 2 == 0]
fibs = []
for num in nums:
    if sum(fibs) < 4000000:
        fibs.append(num)
        a = num + nums[-1]
        fibs.append(a)
